# syntax=docker/dockerfile:1

############################
# Set the base image with CUDA and cuDNN
############################
# CUDA and Ubuntu Versions
ARG CUDA_VERSION=12.8.1
ARG UBUNTU_VERSION=22.04

# Base image
FROM nvidia/cuda:${CUDA_VERSION}-cudnn-devel-ubuntu${UBUNTU_VERSION}

############################
# Install Python, PyTorch, and other dependencies
############################
# Python version
ARG PYTHON_VERSION=3.10
# PyTorch versions
ARG TORCH_CUDA=cu128
ARG TORCH_VERSION=2.10.0
ARG TORCHVISION_VERSION=0.25.0

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1
# Install Python and other apt packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    python${PYTHON_VERSION} \
    python${PYTHON_VERSION}-dev \
    python3-pip \
    python3-venv \
    build-essential \
    git curl wget ca-certificates \
    ffmpeg \
    libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/* \
    && ln -sf /usr/bin/python${PYTHON_VERSION} /usr/bin/python \
    && ln -sf /usr/bin/python${PYTHON_VERSION} /usr/bin/python3 \
    && ln -sf /usr/bin/pip3 /usr/bin/pip
# pip upgrade
RUN pip install --upgrade pip setuptools wheel
# Install PyTorch and torchvision
RUN pip install \
    torch==${TORCH_VERSION} \
    torchvision==${TORCHVISION_VERSION} \
    --index-url https://download.pytorch.org/whl/${TORCH_CUDA}
# Install other Python libraries
WORKDIR /workspace
COPY requirements.txt /workspace/requirements.txt
RUN pip install -r requirements.txt

############################
# Create non-root user
############################
ARG USERNAME=developer
ARG UID=1000
ARG GID=1000
RUN groupadd -g ${GID} ${USERNAME} \
    && useradd -m -u ${UID} -g ${GID} -s /bin/bash ${USERNAME} \
    && chown -R ${UID}:${GID} /workspace
USER ${USERNAME}
